---
- hosts:
    - k8s_master
    - k8s_worker
  roles:
    - k8s-commons-down
- hosts: all
  roles:
    - docker-down
- hosts:
    - raspbian
    - ubuntu
  roles:
    - debian-down
- hosts: ubuntu
  roles:
    - ubuntu-down
- hosts: raspbian
  roles:
    - raspbian-down
- hosts: raspberry_pi
  roles:
    - raspberry-pi-down
