---
- hosts: raspberry_pi
  roles:
    - raspberry-pi-up
- hosts: raspbian
  roles:
    - raspbian-up
- hosts: ubuntu
  roles:
    - ubuntu-up
- hosts:
    - raspbian
    - ubuntu
  roles:
    - debian-up
- hosts: all
  roles:
    - docker-up
- hosts:
    - k8s_master
    - k8s_worker
  roles:
    - k8s-commons-up
- hosts: k8s_master
  roles:
    - k8s-master-up
  run_once: yes
- hosts: k8s_worker
  roles:
    - k8s-worker-up
